[package]
name = "wharf"
version = "0.2.0"
edition = "2021"
author = "Duke of Stars"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive"] }
colored = "2.0.0"
